### ISSUE TITLE
Client端的CYarpConnectionFactory类创建到目的地的通道疑似socket未能正常关闭，导致一直在通讯

### ISSUE THREAD

**Issue by lison666** [xljiulang/CYarp#11]
如题，最近使用了cyarp，但是接口方出现 Too many open file 疑似socket未能关闭，
然后翻阅NetworkStream文档，发现ownsSocket=true 即可解决

**Comment by xljiulang** [comment]
你是正确的，默认构造器的ownsSocket值为false
