### ISSUE TITLE
TCP转发可以实现吗

### ISSUE THREAD

**Issue by sunkejava** [xljiulang/CYarp#4]
看代码,支持转发的是http及https,测试了下转发本地一个TCP端口数据,没法接收

**Comment by xljiulang** [comment]
不支持非http协议的tcp端口转发，因为设计是一个server端口，对应n个client，而tcp转发会消耗n个server端口，和本项目的理念冲突

**Comment by bnuzhouwei** [comment]
是不是在客户端实现一个TCP和HTTP的桥接器就能实现了
