### ISSUE TITLE
Unable to host on IIS or AzureAppService

### ISSUE THREAD

**Issue by savage8811** [xljiulang/CYarp#9]
Hi, first, nice project,

for testing purposes I tried to host the CYarpServer on an AzureAppService and also on a WindowsServerVM with IIS.
In both cases I get a Status 502 BadGateway when I make a request with PostMan.

If I start and try everything locally, it works like a charm.

Any idea what i am doing wrong?
TY

**Comment by xljiulang** [comment]
1.  Only when the kestrel server is used directly instead of iis (http.sys) or nginx as the front http server, the complete client interaction protocol is supported;
2.  If a front-end http server is necessary, it only supports the websocket interaction protocol. At the same time, CYarp.Client must use ws or wss to connect to CYarp.Server.

**Comment by savage8811** [comment]
Thank you for that clarification. - Is there any chance to support in future a front-end server? Because I host multiple websites with IIS on a VM so I can't start CYarp/Kestrel directly on port 80/443. (I don' want to use different ports)

**Comment by Misiu** [comment]
@xljiulang, any plans to support an IIS server as a host?
I'm not sure if that would be technically possible, and what changes are needed, but looking forward to getting more information..

**Comment by xljiulang** [comment]
Host on IIS is supported, but  CYarp.Client must use ws or wss to connect.
CYarpClient --ws(wss)--> IIS(nginx) --ws--> CYarpServer

**Comment by Misiu** [comment]
@xljiulang thank you for the response.
The plan is to host the server on IIS and to have the clients built as a Windows Service and run them inside a private network.
The goal is to have a single service (client) that can be accessed locally and via CYarp.

In theory, we can use:
```c#
kestrel.ListenAnyIP(8080);
kestrel.ListenCYarp(5000);
```

But I ned to check if that will work.
Do you allow such a scenario?

**Comment by xljiulang** [comment]
This scenario is already natively supported. You need to develop a client (httpServer) based on CYarp.Client.AspNetCore and use the following code to listen:
```c#
// http://{LAN IP}:8080
kestrel.ListenAnyIP(8080);

// request from https://cyarp-server.com by cyarp
kestrel.ListenCYarp(new CYarpEndPoint
{
    // only ws or wss is supported on IIS
    ServerUri = new Uri("wss://cyarp-server.com"),
    ConnectHeaders = { { "Authorization", "some value" } }
});
```

**Comment by Misiu** [comment]
@xljiulang thank you for all the replies.
I've succesfully created two sample projects using your packages.

I created two client projects, and when I used the same header in client's appsetting only the first client gets connected.
Can this be checked from the client's code?

For example, lets assume we have this:
```
public class ClientIdProvider : IClientIdProvider
{
    public ValueTask<string?> GetClientIdAsync(HttpContext context)
    {
        var clientId = context.Request.Headers["ClientId"].ToString().ToLower();
        return ValueTask.FromResult<string?>(clientId);
    }
}
```

and in our client we have:
```
  "CYarpEndPoint": {
    "ServerUri": "http://localhost",
    "ConnectHeaders": {
      "ClientId": "DEV1"
    }
  }
```

When you start two client's with the same ClientId I see some warnings:

<img width="1918" height="1028" alt="Image" src="https://github.com/user-attachments/assets/ccdbdc25-c2ff-406a-ab99-a6477da04d9f" />
I cloned the repo and that the error is comming from `CYarpConnectionListener`, this line:
```
Log.LogConnectError(this.logger, this.endPoint.ServerUri, "连接被中断");
```

I get situation when two clients connect and disconnect so you get content from first, then second client when sending requests to the server.


1. Is there a way to disable connection entierly? So when first app get's connected the second won't conenct (in situation where both share the same ClientId)
2. ~~How does the auth betwen server and client works? How can we validate (using a custom header) that this ClientId can conenct to the server? In samples there is Authorization header with Bearer token, but I'd like to use custom header with API key~~ This was quite easy actually
3. Do SSE and SignalR works when used with Cyarp? I'd like to be able to expose some events from Client when using your channel: Use case: you have a single frontend application that allows you to view logs for a given device, you select device, click on connect and you get SSE or SignalR connection to that specific device using CYarp. 
4. Are there any limitations in request time and size? Can we for example upload large files using CYarp?
5. I'd like to translate all the comments and errors into English. I created PR, comments are welcome - https://github.com/xljiulang/CYarp/pull/18

**Comment by Misiu** [comment]
Quick update on SSE and SignalR.

SSE has some errors: - https://github.com/xljiulang/CYarp/issues/19
SignalR - initial testing looks ok, need ot check if I find something.

P.S.
How do you set the protocol per clinet?

This is a screenshot from sample projects in this repo.

<img width="387" height="55" alt="Image" src="https://github.com/user-attachments/assets/33f45394-2ff0-41fd-9c82-3b66f78406e3" />

I run them via Visual Studio.
